spring:
    datasource:
        url: jdbc:${DB_JDBC:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mshome}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        generate-ddl: on
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                jdbc:
                    lob:
                        non_contextual_creation: true
                enable_lazy_load_no_trans: true

auth:
    username: ${DEFAULT_USERNAME:ms-homeUser}
    password: ${DEFAULT_PASSWORD:ms-home123}
    role: SS_MS_HOME

telegram:
    token: ${TELEGRAM_TOKEN:5903834488:AAG6LMsYNgqkeNYQ9QX5hd3NYpxdXR4pHUE}
    username: ${TELEGRAM_USERNAME:kvproduktabot}

minio:
    url: ${MINIO_SERVICE_URL:http://localhost}
    port: ${MINIO_SERVICE_PORT:9000}
    bucket: ${MINIO_SERVICE_BUCKET:house}
    access: ${MINIO_SERVICE_ACCESS_KEY:minioadmin}
    secret: ${MINIO_SERVICE_SECRET_KEY:minioadmin}

jwt:
    secret: secret_key